[profile.default]
solc = "0.8.24"
evm_version = "cancun"
via_ir = true
bytecode_hash = "none"
optimizer_runs = 9_999_999
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "seaport-types/=lib/seaport-types/",
    "forge-std/=lib/forge-std/src/"
]
